// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../uniquejava/video-editor-wails/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "recording:failed": main$0.RecordingFailedEvent;
            "recording:finished": main$0.RecordingFinishedEvent;
            "recording:status": main$0.RecordingStatusEvent;
        }
    }
}
