// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Clip {
    "id": string;
    "start": number;
    "end": number;
    "sourceUrl": string;
}

export interface RecordingFailedEvent {
    "message": string;
}

export interface RecordingFinishedEvent {
    "path": string;
    "mediaUrl": string;
    "duration": number;
}

export interface RecordingOptions {
    "sourceId": string;
    "sourceKind": string;
    "systemAudio": boolean;
    "microphone": boolean;
}

/**
 * RecordingStatusEvent is emitted while a session is active (and when state changes).
 */
export interface RecordingStatusEvent {
    "recording": boolean;
    "paused": boolean;

    /**
     * seconds of recorded content (excludes pause)
     */
    "elapsed": number;
}
