// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as capture$0 from "./internal/capture/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportVideo(): $CancellablePromise<string> {
    return $Call.ByID(3950637192);
}

export function GetClips(): $CancellablePromise<$models.Clip[] | null> {
    return $Call.ByID(2337220496);
}

export function IsRecording(): $CancellablePromise<boolean> {
    return $Call.ByID(871398354);
}

export function ListSources(): $CancellablePromise<capture$0.Source[] | null> {
    return $Call.ByID(577334471);
}

export function MediaDir(): $CancellablePromise<string> {
    return $Call.ByID(3446629764);
}

export function RequestScreenAccess(): $CancellablePromise<boolean> {
    return $Call.ByID(4120925098);
}

export function SetClips(clips: $models.Clip[] | null): $CancellablePromise<void> {
    return $Call.ByID(4151990852, clips);
}

export function StartRecording(opts: $models.RecordingOptions): $CancellablePromise<void> {
    return $Call.ByID(2286208120, opts);
}

export function StopRecording(): $CancellablePromise<$models.RecordingFinishedEvent> {
    return $Call.ByID(2215676598);
}
