// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface MicDevice {
    "id": string;
    "name": string;
    "default": boolean;
}

export interface Source {
    "id": string;
    "kind": string;
    "name": string;
    "width": number;
    "height": number;

    /**
     * raw base64 PNG without data-uri prefix
     */
    "thumbnail": string;
}
